### ISSUE TITLE
Switch to poetry for dependency management

### ISSUE THREAD

**Issue by willzeng** [unitaryfund/ucc#78]
We can switch to using `poetry` for dependency management like in `mitiq` and in `metriq-gym`. We can add the linter/formatter as well like in https://github.com/unitaryfund/metriq-gym/pull/22

**Comment by jordandsullivan** [comment]
@vprusso @cosenal Would you be able to help support the UCC team on this one since you set this up recently for Metriq gym? :)

**Comment by vprusso** [comment]
Hey @jordandsullivan 

I think the general approach here that I would take would be:

1. Remove `setup.py` and `requirements.txt` from the root directory of the project. 
2. Include a `pyproject.toml` file in the root directory that looks something like this:

```toml
[tool.poetry]
name = "ucc"
version = "0.1.0"
description = "Unitary Compiler Collection: A quantum circuit interface and compiler for multiple quantum frameworks"
authors = ["Jordan Sullivan <jordan@unitary.foundation>", "Misty Wahl", "Nate Stemen"]
license = "GPL-3.0"
readme = "README.md"
repository = "https://github.com/unitaryfund/ucc"
packages = [{ include = "ucc" }]

[tool.poetry.dependencies]
python = ">=3.12"
qiskit = ">=1.3.0"
qiskit-qasm3-import = "0.5.1"
cirq-core = ">=1.4.0"
pytket = ">=1.3.0"
qbraid = ">=0.7.3"
ply = ">=3.11"

[tool.poetry.group.dev.dependencies]
pytest = ">=6.0"
pytest-cov = ">=2.10"

[tool.poetry.group.doc.dependencies]
sphinx = "8.1.3"
myst-parser = ">=0.15"

[tool.poetry.scripts]
ucc = "ucc.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
3. I would remove `VERSION.txt` as well as this information should be able to be managed by the `pyproject.toml` file and is also captured in the `_version.py` file (but perhaps this can be removed as well and consolidated in one location to minimize version number changes).
4. The `Dockerfile` will also need to use `poetry` and not `requirements.txt`. So something like: 
```docker
FROM python:3.12-slim

# Install system dependencies (including GNU Parallel)
RUN apt-get update && apt-get install -y parallel curl && rm -rf /var/lib/apt/lists/*

# Install Poetry
ENV POETRY_VERSION=1.8.3
RUN curl -sSL https://install.python-poetry.org | python3 -

# Ensure Poetry is added to PATH
ENV PATH="/root/.local/bin:$PATH"

# Copy the entire project into the container
COPY . /ucc

# Set the working directory to the root of your project
WORKDIR /ucc

# Install dependencies using Poetry
RUN poetry install --no-root --no-interaction --no-ansi

# Install the `ucc` package itself
RUN poetry install --no-interaction --no-ansi

# Ensure the virtual environment is properly activated
ENV VIRTUAL_ENV=/ucc/.venv
ENV PATH="/ucc/.venv/bin:$PATH"

# Show installed package details
RUN poetry show ucc
```
5. Now the `readthedocs.yml` file also needs to be changed, but I'm not sure how best to do this. Perhaps there are some templates we can borrow from `mitiq`?

There might be some minor things I am missing (like updating the `README.md` to include steps to use `poetry` instead of `pip`), but that should be the bulk of it!

Hope that helps, and feel free to reach out if we can help more!
